### ISSUE TITLE
realtime audio IO

### ISSUE THREAD

**Issue by benbiles** [x42/libltc#16]
Hi, I'm looking for a way to write / read audio frames ( data )  to / from a libltc buffer for decoding encoding LTC audio.

I found this line of code in the tests folder 
n = fread(sound, sizeof(ltcsnd_sample_t), BUFFER_SIZE, f);

am I right in thinking this line is reading in frames of audio from the file ?

I'd like to read / write to from DAC/ADC wired up to an arduino using libltc.

I could bring in samples from I2S on an arduino duo with the I2S library but I'm also thinking
the Manchester encoded LTC would probably survive 8bit 16khz audio over PWM on a arduino uno.

before I try and code this I just wondered if there is something in the library that already supports reading / writing to from audio codec hardware ? or the library is mainly setup for jack and ALSA in lunux ?

sorry for my simple questions here. I'm not the best C programmer and don't want to reinvent the wheel if the library is already doing what I want ?

thank, ben

**Comment by x42** [comment]
Yes that test tool reads raw 8bit samples from a file (8bit is more than sufficient for LTC 16KHz as well)

The library is not concerned with hardware audio i/o,  it just parses raw PCM audio data (decoder) and generates raw 8bit PCM.  It works on any platform.

As for Arduino, the harder part is to strip the library down. Even though the lib is small it's a tight fit with only 640 bytes heap (small audio PCM buffer, biphase state and  at least 1 LTC frame).

bt;dt:  http://gareus.org/gitweb/?p=arduino.git;a=tree;f=ltcsmpte;  is a Arduino LTC  7segment display reader project from 2008. No idea if it still runs on moder Arduinos.  It needed  a trick (IRQ timer) to sample audio at high enough rate (just over 8KHz) on the analog port. I dare say recent Arduinos will make this a lot easier.

**Comment by benbiles** [comment]
Hi, thanks for the link to the reader code, I noticed it depends on #include <FrequencyTimer2.h>
do you still have a copy of this ? Is this your IRQ timer for audio samples input ? 

Also, did you ever make a sripped down ltc encoder for arduino ? I'm try to do both read and write.  maybe I can rewrite the PCM reader and change to reader. 

I'm looking at adding a TCXO hardware clock too for the generator as I dought the arduino is accurate enough for a clock. In that case, do you think I'm better starting the code from scratch using your arduino stripped down decoder as the base?
I think I can understand how your decoding the 80bit ltc frames but not sure how the IRQ samples clock or the LTC timer is working.

**Comment by x42** [comment]
The Arduino work was done with libltc's predecessor, so it's probably the header file from: 
https://svn.code.sf.net/p/ltcsmpte/code/libltcsmpte/trunk/src/ltcsmpte/ltcsmpte.h

Come to think of it, libltc may be sufficient, a lot of the lessons learned from ltcsmpte are in libltc.
That old project was targeted for an Arduino Diecimila. I just checked and the Arduino Uno has twice as much SRAM and the available Flash memory is nearly 31.5K (compared just under 14K on the Diecimila). I suggest to just compile libltc and test.

ie. check how much total Flash RAM the following requires:
```
#include <ltc.h>

main {
    LTCDecoder* decoder = ltc_decoder_create (
            320 /*audio-frames per video-frame, 8K/25 */,
            1 /* small queue, to save precious memory*/);

    while (1) {
        ltcsnd_sample_t  input_sample = 0;

        // TODO: get one sample from the ADC, store it in input_sample (8bit unsigned)

        ltc_decoder_write (decoder, &input_sample, 1, 0 /* ignore absolute alignment*/);

        LTCFrameExt frame;
        while (ltc_decoder_read (decoder, &frame) > 0) {
            // TODO call
            function_that_copies_the_timecode_for_later_display (&frame);
        }
        // TODO sleep until next sample is available
    }
}
```
For the final version,  a callback every 0.125ms will much preferred over sleeping/poll.

There was no `FrequencyTimer2.h` in 2007/8 either.   If you there's an easy way to get digital 8bit samples from an input at ~8KHz or more, you should be all set.



I never wrote an encoder, there are two issues to to take into account: 
*  the arduino's clock is not very stable. depending on environmental conditions (temperature, power supply,..) there is drift.  I don't know how recent Arduinos fare, but a clock-test 25Hz pulse (assuming 25fps) should tell.
*  there's no absolute reference point, re-powering resets the clock. I don't think the Uno has RTC, either.

**Comment by benbiles** [comment]
I already succesfuly compiled libltc on arduino UNO and it only complained about one line ( the reading or writing to file line ) commented out and it compiled. 
I'll try and get some audio input working through a PWM pin and see if it decodes LTC to a serial console.
I've ordered a TCXO oscilator and will try and make RTC for the arduino so it has more reliable LTC encoder output. not sure how I will add that to the code. maybe I can get FrequencyTimer2.h to use my added RTC rather than change libltc. 
I'm asuming the libltc can modulate the 0's 1's into fsk for the LTC audio output ? or I need to code that ? 
Will report back here if I get stuck and/or if it works :)

**Comment by x42** [comment]
That file i/o is `tests/*c` is only for the self-test code (compare against a reference file).  Since you cross-compile you can't run this part on the host anyway, it's fine to remove it. You don't even need to compile those files.

libltc's encoder generates 8bit PCM audio samples, the output is not a sharp on/off (0, 255) but a smooth transition since the specifications demand 40 us +/- 10 usec rise-time of the signal (in the digital world this helps to reduce the gibbs effect on a bandlimited signal).  By default you also get a -3 dBFS signal in the range (38, 218),  one can override both with `ltc_encoder_set_filter (e, 0);`  and `ltc_encoder_set_volume (enc, 0);` respectively.

Anyway, it sounds like a cool project, please keep us posted!

**Comment by benbiles** [comment]
great! so I should just be able to copy the 8bit samples direct to the codecs output variable?

I just got a Wolfson Codec working with the arduino with 8 bit audio IO on a kind of home made shield.
nor very pretty but its working :)

I coppied decoder.c into the arduino code file for the audoi codec IO and this builds fine with the decoder.h included.

I have LTC timecode generated from an android app on my phone.

I'm not sure if decode.c should be in void main() or if I need to just define "decoder.h" in the arduino code and then call the functions to decode or encode the ltc ?

either way , which variable do I copy the audio samples to  / from to pass samples to and from the codec ?

I'm keeping a log of the project here on hackaday https://hackaday.io/project/7694-arduino-smpte-timecode-ltc-reader-generator and I'll keep linking back to this github so other people can find this library :)

**Comment by x42** [comment]
libltc generates *unsigned* 8bit audio, depending on what the codec expects you may have to subtract 127, but otherwise yes, you can just copy the buffer.

For each sample that you receive from the codec, call  `ltc_decoder_write()` 
If you get a complete buffer worth of samples at a time:  `ltc_decoder_write (decoder_object,  buffer_pointer, number_of_samples_in_buffer,  optional_timestamp);`

this function also expects unsigned audio, and there are a few wrappers for other data-formats, see the documentation at http://x42.github.io/libltc/ltc_8h.html#aba7abd60b63023f67d17f30888fa492e

**Comment by benbiles** [comment]
awsome , will post back if I get this working :)

**Comment by benbiles** [comment]
used this and get error,

decoder = ltc_decoder_create(apv, 32);
unsigned char decodeaudiosamples = (unsigned int)left_out;
ltc_decoder_write(decoder,decodeaudiosamples,8,0);
Arduino: 1.6.5 (Mac OS X), Board: "Arduino Uno"

TIMECODE_MAIN1.ino: In function 'void loop()':
TIMECODE_MAIN1:77: error: invalid conversion from 'unsigned char' to 'ltcsnd_sample_t* {aka unsigned char*}' [-fpermissive]
In file included from TIMECODE_MAIN1.ino:32:0:
ltc.h:436: error: initializing argument 2 of 'void ltc_decoder_write(LTCDecoder*, ltcsnd_sample_t*, size_t, ltc_off_t)' [-fpermissive]
 void ltc_decoder_write(LTCDecoder *d,
      ^
invalid conversion from 'unsigned char' to 'ltcsnd_sample_t* {aka unsigned char*}' [-fpermissive]


Guess I'll have to di deaper into the audio codec sample code part and see if I can copy individual samples accros with ltc_decoder_write(decoder,decodeaudiosamples,8,0);

how to I know how many samples to pass ? size_t  ?
is it the number if samples per frame ?

I'll dig deaper into the audio codec lib and see if I can find out..

**Comment by x42** [comment]
The function expects a pointer to the buffer.  if it's a single sample, reference it using `&` like I outlined in the example code above.

**Comment by benbiles** [comment]
it compiled when I used the & pointer.

decoder = ltc_decoder_create(1920, 32);   // why 1920?? depends on FPS??
unsigned char decodeaudiosamples = (unsigned int)left_out;  
// left_out are the audio samples, 4 at a time i think ?
ltc_decoder_write(decoder,&decodeaudiosamples,1,0);

SMPTETimecode stime;
                      ltc_frame_to_time(&stime, &frame.ltc, 1);
                       Serial.print(stime.hours),(stime.mins),(stime.secs);

No idea how to print the timecode output from the decoder.c library to know if its working or not.

I'm using this audio library and its really confusing as to where the samples come form and if they are one at a time! theres all sorts of hysterisis and averaging going on in there.. 

https://github.com/soundspotter/ArduinoUNO_AudioCodecMikroe506/blob/master/AudioCodec/AudioCodec.h

Also I have no idea how to know what samples per video frame should be, that depends on 25 or 30fps ? can the library detect this ?

anyway, leave this if your busy ! I'll just post here as I go , in case its useful for someone else ...

**Comment by benbiles** [comment]
Hi, 

Is there any way to hack ltclib to handle unsigned int samples ?

my codec uses unsigned int and not unsigned char , so if i need to point to the buffer with something like,

ltc_decoder_write(decoder,&audiobuffer???????, 1, 0);

I tried adding a copy from unsigned int to unsigned char and then pointing to that but I have this  ISR(TIMER1_COMPA_vect, ISR_NAKED) in the interupt of the audio codec code. so the copy does'nt work...

any idea what to try next ?

**Comment by x42** [comment]
can you be more specific?  unsigned int is 32bit, but it's highly unlikely that the codec produces 32bit samples. more likley 16bit.

```
unsigned int my_unsigned_int16_audio_signal = READ_FROM_CODEC;
unsigned char val =  (my_int16_audio_signal >> 8) & 0xff; // assumes 16bit unsigned in a 32bit int
ltc_decoder_write (decoder, &val, 1, 0);
```

16bit samples have a range from  zero to 2^16 = 65536.   8 bit samples from zero to 2^8 (256). so basically all you have to do is divide by  65536 / 256 = 256.  This is equivalent to a bit-shift of 8.  The operator  `>> 8` is a lot more efficient for that.

ltc_decoder_write () takes an *array* of samples as parameter.  A c-array is a *pointer* to the first element.  To pass a single value (array length one), one usually passes a pointer to the variable (the ampersand) `&val`.   You cannot pass a pointer to the int (since that's 32bit wide), it must be a pointer that matches the expected array (1 byte, aka unsigned char).

**Comment by benbiles** [comment]
yes I think the samples are 16bit
If i add the code here the copy fails becasue of ISR_NAKED. I think I need this since arduino is'nt very fast ?

error is,

TIMECODE_MAIN1.ino: In function 'void __vector_11()':
TIMECODE_MAIN1:108: error: local frame unavailable (naked function?)
local frame unavailable (naked function?)

I think i need to add code in the interupt somewhere here.. 

// timer1 interrupt routine - all data processed here
  ISR(TIMER1_COMPA_vect, ISR_NAKED) { // dont store any registers
// &'s are necessary on data_in variables

AudioCodec_data(&left_in, &right_in, left_out, right_out);   // passthrough audio input to output
  
  // our sinewave is now in temp2
  left_out = right_in; // put incoming audio on left channel
  right_out = right_in; // put sinusoid out on right channel

// 
unsigned int audio_signal = &right_in;
unsigned char val =  (audio_signal >> 8) & 0xff; // assumes 16bit unsigned in a 32bit int
ltc_decoder_write (decoder, &val, 1, 0);

  reti(); // dont forget to return from the interrupt
}


The codec info is here.. 

https://github.com/soundspotter/ArduinoUNO_AudioCodecMikroe506

**Comment by x42** [comment]
`decoder = ltc_decoder_create(samplesperframe,0);`   should be done once, during initialization.
also decoder_read  and Serial.write() should be done in main(), not in the IRQ handler.

The general concept:  use the decoder to decouple realtime audio  and  data-analysis/print.

The audio-thread (IRQ)  feeds the decoder with data.
The main thread  checks the decoder at regular intervals and displays the timecode.

**Comment by benbiles** [comment]
this compiles runs , but I get a short burst of random characters in the serial terminal before it stops..
000���11I00�8?+0000-000-1000-1100-10"+0400#+0300$+0

the audio passthrough continues though, so its not hanging at least ! so having the copy in loop() improved things !!

I tried some delays in the loop() but did'nt help..


// setup codec parameters
// must be done before #includes
// see readme file in libraries folder for explanations
#define SAMPLE_RATE 8 // 8kHz (WM8731@12.288MHz, Arduino@16MHz) ) mkc 9/15/13
#define ADCS 0 // use no ADCs (potentiometers)
#define ADCHPD 1 // High pass filter on the codec on/off
// WM8731 Microphone control
#define MUTEMIC 0 // disable MUTEMIC
#define INSEL 1 // enable MIC input
#define MICBOOST 0 // enable MICBOOST
#define BYPASS 0 // Bypass LINEIN
#define DACSEL 1 // Select DAC for audio loopback
#define SIDETONE 0 // Deselect SIDETONE
#define SIDEATT 0

// include necessary libraries
#include <Wire.h>
#include <SPI.h>
#include <AudioCodec.h>

// define & include stuff that libltc needs here
#include "ltc.h"
#include "encoder.h"
#include "decoder.h"

#define BUFFER_SIZE (1024)

int samplesperframe = 320;  // 8khz/ 25fps samples per frame
LTCDecoder *decoder;  //  what is this ?
LTCFrameExt frame;    //  what is this ?

unsigned char samples = 00000000;  // maybe faster to use temp variable ( when i try i get errors )

/// end difine things for libltc

// create data variables for audio transfer
// even though there is no input needed, the codec requires stereo data
int left_in = 0; // in from codec (LINE_IN)
int right_in = 0;
int left_out = 0; // out to codec (HP_OUT)
int right_out = 0;

void setup() 
{
  // call this last if you are setting up other things
  AudioCodec_init(); // setup codec and microcontroller registers
  Serial.begin(115200);

  decoder = ltc_decoder_create(samplesperframe,0);  // create ltc decoder called decoder with n samples per frame
}

void loop() 
{
samples =  (right_in >> 8) & 0xff; // assumes 16bit unsigned in a 32bit int  / signed int 16bit to unsigned char 8 bit , is this ok?
ltc_decoder_write (decoder, &samples, 1, 0);

//  int temp1;
//  int temp2;
//  MultiSU16X8toL16(temp1,temp2, &right_in);   // MOD multiplyer 16bit signed - 8bit unsigned char, faster than copy?

// Serial.write((char)(samples >> 8));  // for testing print the upper bits of sample as character 

                   SMPTETimecode stime;
                   ltc_frame_to_time(&stime, &frame.ltc, 1);
                   Serial.print(stime.hours);
                   Serial.print(stime.mins);
                   Serial.print(stime.secs);
                   Serial.print(stime.frame);

                
while (1); // reduces clock jitter   ( do i need this? )
}

// timer1 interrupt routine - all data processed here
ISR(TIMER1_COMPA_vect, ISR_NAKED){ // dont store any registers     

// &'s are necessary on data_in variables

AudioCodec_data(&left_in, &right_in, left_out, right_out);   // 

// our sinewave is now in temp2
  left_out = right_in; // put incoming audio on left channel
  right_out = right_in; // put sinusoid out on right channel

  reti(); // dont forget to return from the interrupt
}

**Comment by x42** [comment]
`LTCDecoder *decoder; // what is this ?`

it is a pointer to the "Decoder object"  (internal state of the LTC decoder).  The decoder object is created  with  `ltc_decoder_create`


`LTCFrameExt frame; // what is this ?`

it is a `struct`  a data-structure representing the LTC data.  (80 bits wide). 

I'm sorry, but I really think you should get some basic C class, or book.

I think you'll want something like this:

```
void setup()
{
    AudioCodec_init();
    Serial.begin(115200);
    decoder = ltc_decoder_create(samplesperframe,0);
}

void loop()
{
    LTCFrameExt frame;
    while (ltc_decoder_read (decoder, &frame) > 0) {
               SMPTETimecode stime;
               ltc_frame_to_time(&stime, &frame.ltc, 1);
               Serial.print(stime.hours);
               Serial.print(stime.mins);
               Serial.print(stime.secs);
               Serial.print(stime.frame);
    }
}

ISR(TIMER1_COMPA_vect, ISR_NAKED)
{ 
    AudioCodec_data (&left_in, &right_in, left_out, right_out);
    unsigned char sample = ((right_in + 32768) >> 8) & 0xff;  // signed 16bit to unsigned 8bit
    ltc_decoder_write (decoder, &sample, 1, 0);
}
```

**Comment by benbiles** [comment]
Yer your right, i'm new to C, I'll order a book today , any recomendations for beginers ? sometihng that deals with variable types buffers etc would be useful !

I tried doing the copy in the TIMER section as above , but I get this error.. ISR_NAKED prevents
this funciton ltc_decoder_write (decoder, &sample, 1, 0) being called.. 

and if I do the copy in the loop(); I get the same random characters..

unsigned char sample = ((right_in + 32768) >> 8) & 0xff;
ltc_decoder_write (decoder, &sample, 1, 0); 

error;

TIMECODE_MAIN1.ino: In function 'void __vector_11()':
TIMECODE_MAIN1:83: error: local frame unavailable (naked function?)
local frame unavailable (naked function?)

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by x42** [comment]
I'm closing this issue since Arduino Audio I/O is not really a libltc issue.
Good luck with the project and keep us posted should you publish source code of it.
