### ISSUE TITLE
What kind of Audio should I use with decode

### ISSUE THREAD

**Issue by lunarbase** [x42/libltc#17]
Hi there, I have followed the docs and tried to use a wav file with the decode function but it is not working. I am not sure what format should I use: aiff, wav? what encoding settings?

What I mean is: I am using unsigned 8-bit and it is not working.

**Comment by x42** [comment]
Do you feed raw PCM data - not the wav file itself?
(https://github.com/erikd/libsndfile is the one-stop solution to read audio files and get raw audio).

While libltc internally uses 8bit unsigned. the API allows to feed it various formats.

**Comment by lunarbase** [comment]
ah, I got it. Managed to make it work now! THANKS!
