### ISSUE TITLE
Compiling under Windows + real time decoding

### ISSUE THREAD

**Issue by orso135** [x42/libltc#18]
Hello!
First of all, thank you very much for this code and all the resources provided with it. 
It has been of great help to better understand how to decode LTC from an audio source.

My goal is to integrate this library into a previously written code (on windows) that reads in real time audio data from a soundcard (using ASIO callbacks) and then decodes it.

I compiled libltc under linux (on cloud9, using make and make check) and everything went as expected: the make check was successful and the timecode.raw file was flawlessly decoded.

Unfortunately, while compiling it in Visual Studio and I encountered few problems, but I quickly fixed them:

1. rint() identifier not found (fixed by manually force the code inside the #if macro)
2. return -infinity; "infinity" undeclared identifier. I fixed it by adding the line:
`double infinity =  std::numeric_limits<double>::max()`

However, once I run the `ltcdecode.cpp` with the following parameters (timecode.raw 882) as done in the make check, I get the following output on  terminal:

`* reading from: timecode.raw `
`2000-00-00 +0000 00:05:27:17 |      626     1511`

(that it's coherent with the first two lines of the linux output), but then it returns without decoding the rest.

Do you have any suggestion? Why is it not properly decoding the whole file?

Thank you in advance!

**Comment by x42** [comment]
I don't have any first hand experience with MSVC, but John Emmas created a VC project for Ardour which includes libltc: https://github.com/Ardour/ardour/blob/master/libs/libltc/MSVCltc/ltc.vcproj

As for why the selftest fails I don't know. A shot in the dark: https://msdn.microsoft.com/en-us/library/ktss1a9b.aspx  set  `_fmode = O_BINARY;`

**Comment by x42** [comment]
PS. the latest version 1.2.0 (Nov'15) has a `rint` wrapper for MSVC (maybe I got the `_MSVC_VER ifdef` wrong?!) see https://github.com/x42/libltc/blob/master/src/ltc.c#L30 and no `-infinity`.  Which version did you use?

**Comment by orso135** [comment]
Thank you very much!! It worked!!

I added the following code right before the `fopen` and now the rawfile is decoded properly!

```
#include <stdlib.h>
#include <Fcntl.h>
#include <Errno.h>

	errno_t err;
	int mode;



	err = _get_fmode(&mode);
   if (err == EINVAL)
   {
      printf( "Invalid parameter: mode\n");
      return 1;
   }
   else
      printf( "Default Mode is %s\n", mode == _O_TEXT ? "text" :
              "binary");

   err = _set_fmode(_O_BINARY);
   if (err == EINVAL)
   {
      printf( "Invalid mode.\n");
      return 1;
   }

```
It'd would have taken me ages to figure it out! Thank you!!

Now I'm using libltc-1.2.0 with Visual Studio 2005 and the `-infinity` is here:
https://github.com/x42/libltc/blob/master/src/decoder.c#L106

Tomorrow I'm gonna try to link it with the main code. I hope it won't be too hard!

**Comment by x42** [comment]
Thanks for confirming my suspicion.
I've updated the test/example code to include the `_fmode` (6716dde9) and added support for MSVC `infinity` (9bcda5e).

Don't hesitate to let me know if you encounter further issues.

**Comment by orso135** [comment]
I have no experience with Audio programming and C++ and I am having few problems to connect the library to the some previous code that relies on ASIO.  
I placed a slight modified version of your code (ltcdecode) inside the callback function *bufferSwitchTimeInfo that fills the input buffers. 

```
//callback
ASIOTime *bufferSwitchTimeInfo(ASIOTime* params, long doubleBufferIndex, ASIOBool directProcess)
{	
[...]
//decoding is performed only on a specific input channel
if (audioDriverSettings.bufferInfos[i].channelNum == TIMECODE_CH)
						{
							for (int l = 0 ; l < buffSize ; l++)
							{
								//copying buffer l
								raw_data = *((int*)audioDriverSettings.bufferInfos[i].buffers[doubleBufferIndex]+l);
								//downsampling from 24 to 8 bits
								acquired_data = (size_t) (raw_data >> (24));
								sound[l] = acquired_data;
							}
							ltc_decoder_write(decoder, sound, BUFFER_SIZE, total);
							while (ltc_decoder_read(decoder, &frame)) {
								ltc_frame_to_time(&stime, &frame.ltc, 1);
								//save to file
							}
							total += BUFFER_SIZE;
						}
[...]
}
```

The code compiles without problems, but unfortunately at run time I get the following exception:

> Unhandled exception at 0x00413d10 in GrassFishCaptureMulti.exe: 0xC0000005: Access violation reading location 0x00000028. _Break Continue_

If i press _break_ the code debugger jumps directly to the assembly code, few lines after executing the function decode_ltc:
```
decode_ltc:
00413CF0  push        ecx  
00413CF1  push        ebx  
00413CF2  push        ebp  
00413CF3  push        edi  
00413CF4  xor         edi,edi 
00413CF6  cmp         dword ptr [esp+14h],edi 
00413CFA  jbe         decode_ltc+15Eh (413E4Eh) 
00413D00  mov         ebp,dword ptr [esp+1Ch] 
00413D04  mov         ebx,dword ptr [esp+18h] 
00413D08  jmp         decode_ltc+20h (413D10h) 
00413D0A  lea         ebx,[ebx] 
>>  00413D10  movzx       ecx,byte ptr [esi+28h] 
00413D14  sub         ecx,80h 
00413D1A  mov         eax,ecx 
00413D1C  shl         eax,4 
00413D1F  sub         eax,ecx 
00413D21  cdq              

```
(the instruction with the >> sign is where the code breaks)

If I continue the execution the executed assembly line doesn't change and I receive the same exception again.

The code stops [here](https://github.com/x42/libltc/blob/master/src/decoder.c#L285)
(I tested it by commenting the code from this line up to the end)

Do you have any suggestion/see any problem in my code? 

Am I right to assume that there is memory access violation (like problems with the pointers in the data I'm passing to the library)? If so, do you have any clue on where can be the problem?

Thank you a lot for your support!

**Comment by x42** [comment]
This needs a bit more context.  The machine code is kinda useless without stack and heap.

Was the decoder allocated?  ie. a  `decoder =  ltc_decoder_create (...)` ?
What is the type of `sound`?  is that  `uint8_t  sound[BUFFER_SIZE]` ?
 
`buffSize` vs `BUFFER_SIZE` is a bit confusing.  in this case you'll want
   `ltc_decoder_write(decoder, sound, buffSize, total);`

That cast from  `int  raw_data`   to `size_t` looks odd.   "downsample from 24 to 8"  would be `>>16`, assuming the data is unsigned int.  --  ASIO usually provides `float`.

I suggest to try it a bit  simpler and more explicit at first:
```
for (int l = 0; l < buffSize; ++l) {

  // get sample from audio-device
  int raw_24bit_unsigned_sample = *(int*) .....;

  // convert it to 8bit,  leave it as "int" for now. 
  int raw_8bit_unsigned_sample = raw_24bit_unsigned_sample / 65536;

  // "char" is a uint8_t - explicit overkill cast for sanity :)
  char raw_8bit = (char) raw_8bit_unsigned_sample & 0xff;

  // write one sample at a time, not very efficient but can be optimized later.
  ltc_decoder_write (decoder, &raw_8bit, 1, total);
  ++total;
}
```

if  the audio data is signed 24 bit.  instead use
   `int raw_8bit_unsigned_sample = 32768 + raw_24bit_signed_sample / 65536;`
or float
  `int raw_8bit_unsigned_sample =  128 + raw_float_sample * 127.0;`

Once that works, start consolidating.. 
hope that helps.

**Comment by orso135** [comment]
Thank you for all your suggestions and sorry for the late reply. Before answering I wanted to study a bit better the code and the ASIO documentation.

After your comment I quickly managed to make it run. There were really trivial mistakes (the decoder was not allocated in the main function and apv was not initialized properly), I apologize.

Everything now works flawlessy!

For further references this is how I divided your code inside the old one.

In the `main.cpp`
```
...
#include "ltc.h"
SMPTETimecode stime;
int TIMECODE_CH;
LTCDecoder *decoder;
LTCFrameExt frame;

int apv;
FILE* file_temp_lib; //saving data for testing
int total_timecode;
...
main()
{
...
	total_timecode=0;
        apv = 1920;
	decoder = ltc_decoder_create(apv, 32);
	


..
[instantiating ASIO callback functions]
...
}
```

In the `ASIO_Callback.cpp`
```
#define BUFFER_SIZE (1024) //max buffer
#include "ltc.h"

extern int TIMECODE_CH;
extern SMPTETimecode stime;

extern LTCDecoder *decoder;
extern LTCFrameExt frame;


extern int total_timecode;

extern FILE* file_temp_lib;

int raw_data32bit_for_timecode[BUFFER_SIZE];
ltcsnd_sample_t raw_data8bit_for_timecode[BUFFER_SIZE];
...
[inside the ASIO callback]
...
[for each channel]
...
memcpy (raw_data32bit_for_timecode,((int*)audioDriverSettings.bufferInfos[i].buffers[doubleBufferIndex]),buffSize * sizeof(int));
...
				if (i == TIMECODE_CH) //timecode decoding is done only on one channel
				{
					//downsample from 24 bit to 8
					for (int l = 0 ; l < buffSize ; l++)
					{
						//downsample from 24 bit to 8 (data is in the first 24 bits)
						raw_data8bit_for_timecode[l] = raw_data32bit_for_timecode[l] >> 24;
					}
                                        //decode
				        ltc_decoder_write (decoder, raw_data8bit_for_timecode, buffSize, total_timecode);
					total_timecode=total_timecode+buffSize;


					/* Saving data for testing
					file_temp_lib = fopen("dumptest.raw", "a");
					if (file_temp_lib!=NULL)
					{
						fwrite(raw_data8bit_for_timecode, sizeof(ltcsnd_sample_t), buffSize, file_temp_lib);
						fclose(file_temp_lib);
					}else
						printf("Error reading file");
					
					//printf("sample: %d",ch);
					*/


					while (ltc_decoder_read(decoder, &frame)) {
						printf("Test decode");

						ltc_frame_to_time(&stime, &frame.ltc, 1);

                                        [save to file the timecode]

					}
				}
```

Thank you for your amazing support!

**Comment by x42** [comment]
nice.  I'll close this ticket then.

PS. you may want to un-harcdoe the 1920  audio-samples per video-frame.
here:  48000 / 25  (audio-sample-rate  over expected video-frame-rate) to speed up initial detection. 

Also doing file-i/o or printing inside the ASIO callback is not a good idea (though maybe fine for debugging only)
http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing

I suggest to move the `while (ltc_decoder_read(decoder, &frame)) {..}`  into the main thread.

**Comment by lp35** [comment]
Hi there,

I bring my little stone to the edifice, can you modify

`#if (defined _MSVC_VER && _MSVC_VER < 1800)`

into

`#if (defined _MSC_VER && _MSC_VER < 1800)`

It will fix the compilation error of rint.

Kindest regards,

**Comment by lp35** [comment]
Hi Antithing,

FYI, I'm using the Portaudio API to retrieve the data. It is straight forward API and does not need a lot of time to integrate.
