### ISSUE TITLE
reading live data in windows?

### ISSUE THREAD

**Issue by antithing** [x42/libltc#19]
Hi, thank you for your lib, I have it compiled in visual studio, and the test with a file works great. Now though, I need to get a live input stream working. Is there a windows-friendly version of this around? I am looking at ltc-tools/ltcdump.c, but it seems linux only.

Thanks again.

**Comment by x42** [comment]
jltcdump is not Linux only. OSX, BSD, and other POSIX OSses are fine and it also compiles with mingw for Windows (works using JACK as audio interface abstraction to ASIO).

Still it's a simple command-line tool, not very Windows like and also not a MSVC project.
I'm sorry, I cannot help you there, but maybe someone else can.
