### ISSUE TITLE
Realtime LTC-Out with Raspberry Pi as a NTP-Server

### ISSUE THREAD

**Issue by HansImGlueck43** [x42/libltc#2]
Hello Robin,

I'm a really noob in Linux but anyway, I tried sucessfully turning a Raspberry Pi into an Stratum-1 NTP-Server following these instructions:

http://open.konspyre.org/blog/2012/10/18/raspberry-pi-time-server/

and here:

http://www.satsignal.eu/ntp/Raspberry-Pi-NTP.html

Now it would be fine to have the Realtime LTC-Audio-Signal at the 3,5mm-Jack of the Raspberry, but - as a noob - I have no idea how to get this working...

**Comment by x42** [comment]
@edwar64896 Do you have a link to the project?

**Comment by edwar64896** [comment]
Sorry for the delay in responding.... finally got around to putting this on github.

https://github.com/edwar64896/piltc

It's _really_ alpha, but it's a start.

**Comment by aaroncv3** [comment]
@edwar64896 Excellent to see code for this!  Do you have a reference for the output, such as this:
`GPIO >---||---> TIP`
`_GND >--------> RING`
(Where c = 1uF)?
