### ISSUE TITLE
Using a live input stream?

### ISSUE THREAD

**Issue by antithing** [x42/libltc#21]
Hi, thank you again for your code. I have it working great with the testfile, but am a bit stuck on how to use a live input stream. I have one of these:

http://www.pinknoise-systems.co.uk/tentacle-single-set.html

Which plugs into the mic port of the computer (Windows 10) and streams in LTC data.

Is anyone using live input with this library? If you could point me at an example, or some tips, it would be much appreciated.  Thanks!

**Comment by x42** [comment]
There's  https://github.com/loupus/LtcWaveAudio but that's a generator (not decoder) but it's a fully fledged MSVC project, so it may help.

Also not directly what you ask for, but Ardour is using libltc and there are Windows binaries (it can also be compiled with MSVC):  http://nightly.ardour.org/ has demo versions if you want to play around:

Launch Ardour, create a new session.
Edit > Preferences > Transport    

*   Sync/Slave: External Timecode Source: LTC
*    LTC-reader:   select input port of souncard

Then in the main editor window:  Switch from "Internal" to  "LTC" (button top middle, left of main clock)  and transport should start rolling along.

**Comment by antithing** [comment]
Ok, i will take a look at those. Thanks!

**Comment by x42** [comment]
Closing this. 
Since soundcard i/o is not in the scope of the library this is not an issue per se.
