### ISSUE TITLE
fyi: java wrapper

### ISSUE THREAD

**Issue by BernsteinA** [x42/libltc#22]
@x42 not sure if you got my email; just fyi I've made a java wrapper for this, and am using said wrapper in a commercial, closed source project.

Pretty sure that complies with the LGPL license but I wanted to do due diligence before releasing it commercially.

https://github.com/BernsteinA/libltc-jni

**Comment by x42** [comment]
Thanks a lot!  I have not tested it, but skimmed the code and it looks good.

Yeah, commercial use is fine with the LGPL, even proprietary code can use it as long as you make changes to libltc itself public and allow users who ask to re-link it (in a nutshell).

I've just added a reference in the manual 10174a95a15178.
The doxygen html doc will be updated with the next release.

**Comment by x42** [comment]
Now listed under References on http://x42.github.io/libltc/
