### ISSUE TITLE
Not detecting LTC audio sync

### ISSUE THREAD

**Issue by ehoutsma** [x42/libltc#27]
I'm trying to extract the timecode from my LTC signal created by LTC Timecode Generator (Android) and recorded to 3 different camera's, but the timecode isn't recognized by ltcdump and not consistently recognized by tentacle sync. 

This is what the waveform looks like.
<img width="1102" alt="schermafbeelding 2017-11-01 om 09 39 07" src="https://user-images.githubusercontent.com/12186305/32266816-29119abc-bee9-11e7-8c4f-2dd3717d6ee7.png">

How can I improve the consistency of the LTC, and recognizeblility.

**Comment by x42** [comment]
Wow it's a wonder any LTC can detect all in that signal. LTC is a square wave. Ideally it looks like

![ltc](https://user-images.githubusercontent.com/30246/32272868-4f111564-bf00-11e7-8fca-466d92dd8b18.png)

Your signal looks like it has some hi-pass/DC filter on it (that could explain the sine-like slew)  and/or perhaps clipped and wrapped at 16bit (that may explain the reversed spikes in the sync-word).
If you're lucky it may just be a big/little endian conversion gone wrong (swap the endianess of the .wav)

How did you record it?  Android phone headphones out to camera mic-in without any impedance converter?  Mismatched impedance could also explain this and there's not really a way to recover from this.

**Comment by ehoutsma** [comment]
Android phone headphones to Behringer UCA222, Line out to Sony NX100 Line input. Headphones monitor out to Canon 700D mic input.

Did a quick test with a direct connection between the Android (htc) phone to the 700D. Same garbage. Different android (Samsung) phone, to the 700D, recorded output is much cleaner and ltcdump recognizes the ltc signal.

**Comment by x42** [comment]
OK, that make sense now. 

There are some soundcards which are smart enough to switch to line-out (depending on receiver impedance) not sure about the phones though.  The Sony camera should a switch for line vs mic. level.

But in general you can't directly connect a headphones-output to a mic-input.

Anyway for testing there's http://elteesee.pehrhovey.net/  or grab some example .wav from http://robin.linuxaudio.org/tmp/ltc_25fps_2min.zip or generate some using `ltcgen` (https://github.com/x42/ltc-tools).

**Comment by x42** [comment]
PS. search the web for "headphones-out to mic-in impedance adapter"  there are various explanations and DIY solutions.

I'll close this issue as it's not libltc related.
Good luck with sync'ing!
