### ISSUE TITLE
Unable to link to libltc.so.11

### ISSUE THREAD

**Issue by patrickcusack** [x42/libltc#28]
I downloaded the libltc-1.3.0.tar.gz, ran ./configure, make, sudo make install and then ran gcc against the ltcencode example:

gcc ./ltcencode.c -lltc -o ltcencode

I get the following error:.
/ltcencode: error while loading shared libraries: libltc.so.11: cannot open shared object file: No such file or directory

I used ldd to see the .so being used. It says libltc.so.11. There are two libltc.so files that are installed. One in /usr/local and one in /usr/local/lib.

When I run ls -la on any of the shared libraries, I get the following info
 /usr/local/libltc.so.11 -> /usr/local/lib/libltc.so
/usr/local/lib/libltc.so -> libltc.so.11.0.5
/usr/local/lib/libltc.so.11 -> libltc.so.11.0.5

I assume that either reference to libltc.so.11 resolves to libltc.so.11.0.5.

Any recommendations to get the link working?

**Comment by patrickcusack** [comment]
here's the output of ldd -v ./ltcencode

[hdr@localhost tests]$ ldd -v ./ltcencode
	linux-vdso.so.1 =>  (0x00007ffe92cb7000)
	libm.so.6 => /lib64/libm.so.6 (0x00000037e4c00000)
	libltc.so.11 => not found
	libc.so.6 => /lib64/libc.so.6 (0x00000037e4000000)
	/lib64/ld-linux-x86-64.so.2 (0x00000037e3800000)

	Version information:
	./ltcencode:
		libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
	/lib64/libm.so.6:
		libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
	/lib64/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2

**Comment by patrickcusack** [comment]
okay, setting LD_LIBRARY_PATH to /usr/local/lib fixed the issue

**Comment by x42** [comment]
Do other libraries in `/usr/local` work? perhaps a missing entry in `/etd/ld.conf*`

**Comment by x42** [comment]
PS. what distro is this? libltc is packaged on most distros.

**Comment by patrickcusack** [comment]
I built this: 426 KB libltc-1.3.0.tar.gz <https://github.com/x42/libltc/releases/download/v1.3.0/libltc-1.3.0.tar.gz>  using https://github.com/x42/libltc/releases <https://github.com/x42/libltc/releases>. Adding /usr/local/lib to LD_LIBRARY_PATH addressed the issue.

**Comment by x42** [comment]
Alternatively you can configure it with `--prefix=/usr` ; it depends on your OS what the correct approach is. 

Anyway, have fun with en/decoding LTC!
