### ISSUE TITLE
Avoid buffer copy with ltc_decoder_write_ template

### ISSUE THREAD

**Issue by lp35** [x42/libltc#31]
Hi,

Just as an improvement, I see that the template function ltc_decoder_write_ is reallocating a buffer sized of LTC_CONVERSION_BUF_SIZE on the stack at every call.

It would be interesting to change the decode_ltc parameters instead and add the format of the passed sample, or update the ltc_decoder_create function to support the type of samples?

BR

**Comment by x42** [comment]
What's wrong with using the stack?

Also you don't have to use the provided conversion methods, they're just there for convenience and documented to be wrappers around `ltc_decoder_write`.  Your application can use a pre-allocated region on the heap if need be.
