### ISSUE TITLE
1.3.1 tarball contains 1.3.0 directory

### ISSUE THREAD

**Issue by barjac** [x42/libltc#39]
The release tarball for 1.3.1 contains 1.3.0 directory breaking our (Mageia) rpm spec :(

**Comment by x42** [comment]
Can you be more specific? Which release tar, from where?

I can't reproduce, please try
```bash
curl -L https://github.com/x42/libltc/releases/download/v1.3.1/libltc-1.3.1.tar.gz | tar tz
```

**Comment by barjac** [comment]
Sorry, just found a typo in the spec that I had not noticed.
Thanks for your reply. Closing.
