### ISSUE TITLE
support for decoding 64bit floating-point buffers

### ISSUE THREAD

**Issue by superbigio** [x42/libltc#41]
Hi Robin,

thanks for writing such a simple and clean API.
Your library is working really well for my purposes.

In the app I am working on at the moment I am dealing with Core Audio and 64-bit floating point audio buffers. I see that in your library there is only a wrapper function for decoding 32-bit floats.

`void ltc_decoder_write_float(LTCDecoder *d, float *buf, size_t size, ltc_off_t posinfo);`

I would like to add a wrapper for doubles as well.

If you agree to it, I can send you a PR.
Thanks for your consideration.

**Comment by x42** [comment]
I'm torn.. 64bit float make no sense, in particular when it comes from an analog source.

But yeah.. why not. I'll merge a pull request. So please go ahead.
