### ISSUE TITLE
getting the LTC volume

### ISSUE THREAD

**Issue by superbigio** [x42/libltc#44]
I would like to add support for getting the LTC volume in dBFS:
`double ltc_encoder_get_volume(LTCEncoder *e)`

**Comment by x42** [comment]
Yeah why not.. might be handy to query the 8 bit equivalent.
Do you have a use-case in mind, or is this just for consistency?

**Comment by superbigio** [comment]
Yes, I am wrapping your library into two Max/MSP externals. In Max/MSP terminology the volume is an attribute of the LTC so I need getters and setters for it. I think you have written Max/MSP externals in the past so you know what I mean. In any case being able to query the volume might be handy in a variety of situations. And of course it's also good for consistency in general. Being such a trivial function to write, why not?
Notice that the same could be said for the filter/risetime parameter. I could create a PR for both volume and filter if you want, but so far I haven't had the need to get the rise-time value.
Let me know...

**Comment by x42** [comment]
I'd be happy to pull either.

For use in Max/MSP I'd not expose either, and just offer the smallest API that's required. Leaving fewer ways for users to shoot themselves in the foot.

**Comment by superbigio** [comment]
Ok, I will include them both then. PR on its way...
