### ISSUE TITLE
Renaming a couple of functions

### ISSUE THREAD

**Issue by superbigio** [x42/libltc#45]
I think it would be beneficial to rename
`ltc_encoder_get_buffer`
to
`ltc_encoder_copy_buffer`
since that's what the function is actually doing.

In many APIs I have worked verbs such as 'copy' or  'create' are associated with memory allocations so the user is responsible for releasing the resources allocated. Whereas 'get' is just for retrieving a value or a pointer to something. I personally think it's a pretty good convention to follow. For example in your API `ltc_encoder_get_bufptr` would already follow this idea.

We could temporarily do something like:
`#define ltc_encoder_get_buffer ltc_encoder_copy_buffer`
to avoid breaking code that is using the former name.

Also for consistency with `etc_encoder_get_buffersize`:
`etc_encoder_set_bufsize` should be renamed to `etc_encoder_set_buffersize`

Let me know what you think.

**Comment by x42** [comment]
Your suggestions indeed improve naming consistency.

To avoid breaking the ABI, the old functions should call the new ones, and both need to be exported (header only defines make it hard to maintain compatibility).

The old methods should have some portable `__attribute__((__deprecated__))`, and doxygen  `deprecated Please use ... instead` comments.

For a start perhaps
```
#ifdef __GNUC__ 
#define DEPRECATED_EXPORT __attribute__((__deprecated__))
#else
#define DEPRECATED_EXPORT 
#endif

size_t ltc_encoder_get_buffersize(LTCEncoder *e) DEPRECATED_EXPORT;
```

**Comment by superbigio** [comment]
Yes, totally agree 100%.
I think I am clear on where to go from here.
I am gonna try to send you a PR during this weekend.

**Comment by x42** [comment]
Applied in 2f2352bc48...622e82a0
Cheers!
