### ISSUE TITLE
LTC signal default rise time

### ISSUE THREAD

**Issue by superbigio** [x42/libltc#49]
I am reading the article referenced in the comments of the ltc.h file.
http://www.philrees.co.uk/articles/timecode.htm
It says: "The standard specifies that the LTC signal should have a rise time of 25 µs ± 5 µs."
Is there a particular reason why the LTC encoder defaults to 40 µs?

**Comment by x42** [comment]
SMPTE 12M-1999 specifies it as 40usec.  

I bought the spec a while ago. This is an excerpt from page 7:

![12m](https://user-images.githubusercontent.com/30246/68535386-3a5b2c80-0342-11ea-869f-f4e6a8d664cd.png)

The exponential 1st order low-pass used lib libltc is close-enough and meets the spec. There's usually some Gibbs effect, anyway

**Comment by superbigio** [comment]
I see... thanks for the explanation.
