### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by dsyleixa** [x42/libltc#61]
could you please provide a bash install script fo Raspberry Pi (Stretch & Buster) which installs all and everything, starting with  download, then extract zip or tar archive, then create all directories and links and paths and everything which is required?

**Comment by x42** [comment]
On the debian or raspbian, just use the distro provided libltc and libltc-dev packages.

Other than that please see _Installation_ at http://x42.github.io/libltc/

**Comment by dsyleixa** [comment]
It's too complicated, no idea how to do that, that' why I ask for automatic install programs/scripts.

**Comment by x42** [comment]
The installation process is standard, identical to all other GNU Libraries (using gnu autotools).

I suggest to get familiar with it since it's used for many other libraries as well, also I expect it will help if you actually want to use the library in your own projects.

In general providing a custom script to deploy libraries is also frowned upon by distribution packagers, who prefer to do this specifically for each GNU/Linux distribution.  For Raspberry Pi/debian the library is already available. you do not need a script but can get it directly.

**Comment by dsyleixa** [comment]
I install things via
sudo apt install "packagename"
or via 
git clone git://"path"
cd "libpathname"
./build

e.g., for wirinigPi it once was
git clone git://git.drogon.net/wiringPi
~/wiringPi
./build

so over all  just 1 or max 3 lines.
Your instructions are too vague and confusing - so which are your instructions? perhaps in a script, if more complicated?

**Comment by x42** [comment]
sudo apt install "libltc"

**Comment by dsyleixa** [comment]
thank you, but to me it was not clear what you menat with "distro provided package".
sudo apt install libltc
of course is fine, I only couldn't find that anywhere, this is the explicite Installation instruction which was missing.
OTOH, the "documentation" about installation  is absolutely un-understandable to me.
But now it's fine, thank you!
BTW, which is the compile/build-parameter? (I also didn't find that in your readme)
-llibtc ?

**Comment by x42** [comment]
To develop an application, you'll also need  `apt install libltc-dev`

And in your app build-system you can use pkg-config,  e.g. `pkg-config --libs ltc`

It's a C library, so  `#include <ltc.h>`  -- have a look at the example-code:
https://github.com/x42/libltc/blob/master/tests/example_encode.c
or other projects using the library e.g. https://github.com/x42/ltc-tools

**Comment by dsyleixa** [comment]
ok, thanks a lot!
I don't use pkg-config, I just use  simple cmd lines for C and C++ like 
gcc/g++ -Wall -o  "myfile.c" "exefile"  
so e.g.,
gcc/g++ -Wall -o  "myfile.c" "exefile" -ltc
?
