### ISSUE TITLE
Howto ltc decode S24_3LE ?

### ISSUE THREAD

**Issue by petke** [x42/libltc#73]
Hi

I'm maintaining some Alsa capture code, which samples are then ltc decoded with libtc. I'm very unfamiliar with it so apologies for the possibly ignorant question here.

For Alsa capture format SND_PCM_FORMAT_S16_LE  I can simply use ltc_decoder_write_s16. And for SND_PCM_FORMAT_FLOAT_LE i can simply use ltc_decoder_write_float

But for SND_PCM_FORMAT_S24_3LE there is no similar decode function. I'm unure how that should be done. I guess I should use ltc_decoder_write to write raw samples, but probably need to convert it somehow first.

Any tips?

**Comment by x42** [comment]
simple solution: write 1 sample at a time.

```C
uint8_t *src; // data from ALSA, when mono, n_chn =1.
while (nframe--) {
  ltc_decoder_write (ltcdecoder, &src[2], 1, pos++); // take high-byte
  src += 3 * n_chn; // move to next frame // actual value here   snd_pcm_channel_area_t a;  (a->step >> 3)
}
```

you could also first batch convert it, sth lke
```C++
uint8_t* src; // mmap'ed audio data buffer 
int stride = pcm_channel_area->step >> 3;

int remain = nsamples;
while (remain > 0) {
  ltcsnd_sample_t buf[1024];
  int proc = std::min<int> (1024, nsamples);
  for (int i = 0; i < proc; ++i) {
    buf[i] = src[2 + i * stride];
  } 
  ltc_decoder_write (d, buf, proc, pos)
  pos += proc;
  remain -= proc;
  src += proc * stride;
}
```

**Comment by petke** [comment]
Thank you. That works perfectly.

**Comment by petke** [comment]
Both your versions works fine. Thanks. One final question just to make sure i understand how it works.

```
//int stride = 3;
...
buf[i] = src[2 + i * stride];

```
So we read one byte from src pointer and jump tree bytes of every sample.

So that means ltc decoder only need to read one byte of every three, for this format (the other two bytes are unused and can be garbage)? 

And which one of every 3 bytes is used, is what that 2+ is about?

**Comment by x42** [comment]
with S24_3LE, the data stream has get 24 bits (3 bytes) of data for each sample.

LTC is a square wave, and the decoder only require some low precision basically just "signal above zero, below zero", so 8bits are sufficient.

 Here the highest 8bits (most significant byte) is used. With LE that at offset 2.
